// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdLozkpNi96eyHoQSzYgz_bJCHc_fIvEw',
    appId: '1:170182510659:web:aa5fb56d04cb880da4ecf6',
    messagingSenderId: '170182510659',
    projectId: 'systeme-pv',
    authDomain: 'systeme-pv.firebaseapp.com',
    databaseURL: 'https://systeme-pv-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'systeme-pv.firebasestorage.app',
    measurementId: 'G-T4V35T8L2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8fTGNI7EtJLrFjtrSJO1JEGUZ29LvCSU',
    appId: '1:170182510659:android:8676609fa2fe1316a4ecf6',
    messagingSenderId: '170182510659',
    projectId: 'systeme-pv',
    databaseURL: 'https://systeme-pv-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'systeme-pv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.pvSystemMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.pvSystemMonitor',
  );
}